// Fictional accounts for the beta. These are Microsoft's stock example company names.
// Nothing here is customer data. Real data goes in only after sign in is enabled.

export const SAMPLE_OPPS = [
  { id: "sample-contoso-health", account: "Contoso Health System", opportunity: "Ambient clinical documentation, governance framework, EHR integration", stage: "Qualified", segment: "Healthcare", lead: "Thoughtworks", seller: "Avery", tw: "Strong fit", size: 480000, gmPct: null, closeDate: "2026-11-15", nextStep: "Executive workshop and funding options", notes: "Sample record." },
  { id: "sample-fabrikam-logistics", account: "Fabrikam Logistics", opportunity: "Route optimization agents on Azure AI Foundry", stage: "Proposal / RFP", segment: "ITS", lead: "Zones", seller: "Jordan", tw: "Zones only", size: 260000, gmPct: null, closeDate: "2026-10-30", nextStep: "Finalize phased pricing", notes: "Sample record." },
  { id: "sample-northwind-traders", account: "Northwind Traders", opportunity: "Enterprise IT hardware, software and services supplier consolidation RFP", stage: "Proposal / RFP", segment: "ITS", lead: "Thoughtworks", seller: "", tw: "Not indicated", size: 5200000, gmPct: null, closeDate: "2026-10-05", nextStep: "Submit final proposal", notes: "Sample record. Resale heavy, so the default GM% will overstate margin." },
  { id: "sample-adatum-energy", account: "Adatum Energy", opportunity: "AIOps and observability advisory", stage: "Discovery", segment: "SLED / Public Sector Utility", lead: "Thoughtworks", seller: "Casey", tw: "Potential", size: null, gmPct: null, closeDate: "", nextStep: "Scope advisory workshop", notes: "Sample record." },
  { id: "sample-litware-mfg", account: "Litware Manufacturing", opportunity: "Copilot adoption and AI governance", stage: "Qualified", segment: "ENT", lead: "Zones", seller: "Morgan", tw: "Not indicated", size: 90000, gmPct: 35, closeDate: "2026-09-12", nextStep: "Confirm budget owner", notes: "Sample record with a GM% override and a close date already in the past." },
  { id: "sample-tailspin-air", account: "Tailspin Airlines", opportunity: "", stage: "Discovery", segment: "ENT", lead: "", seller: "", tw: "Not indicated", size: null, gmPct: null, closeDate: "", nextStep: "", notes: "Sample record with every gap flag on." },
  { id: "sample-wingtip-retail", account: "Wingtip Retail", opportunity: "Demand forecasting pilot", stage: "Blocked", segment: "MM", lead: "Zones", seller: "Avery", tw: "Zones only", size: 150000, gmPct: null, closeDate: "", nextStep: "Resolve GPU quota and credit association", notes: "Sample record." },
  { id: "sample-woodgrove-bank", account: "Woodgrove Bank", opportunity: "Fraud analytics on Microsoft Fabric", stage: "Identified", segment: "ENT", lead: "Thoughtworks", seller: "Jordan", tw: "Target", size: null, gmPct: null, closeDate: "", nextStep: "Executive introduction", notes: "Sample record." },
  { id: "sample-proseware", account: "Proseware Legal", opportunity: "Contract review AI and Copilot positioning", stage: "Qualified", segment: "ITS", lead: "Zones", seller: "Casey", tw: "Not indicated", size: 40000, gmPct: null, closeDate: "2026-12-01", nextStep: "Continue Copilot positioning", notes: "Sample record." },
  { id: "sample-coho-winery", account: "Coho Winery", opportunity: "Supply chain analytics", stage: "Won", segment: "MM", lead: "Zones", seller: "Morgan", tw: "Zones only", size: 75000, gmPct: null, closeDate: "2026-08-20", nextStep: "", notes: "Sample record. Closed won." },
];
